arhidoc/arhidoc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("docbase.urls", namespace="docbase")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

arhidoc/docbase/urls.py
from django.urls import path

from . import views

app_name = "docbase"
urlpatterns = [
    path("", views.index, name="main"),
    path("load/<path>/", views.download, name="load"),
    path("all_category", views.all_category, name="all_category"),
    path("docs_category/<pk>", views.docs_category, name="docs_category"),
    path("create_docs<pk>", views.create_docs, name="create_docs"),
    path("searche", views.searche, name="searche"),
]

arhidoc/docbase/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование категории",
        help_text="Введите наименование категории",
    )
    date_created = models.DateTimeField(
        verbose_name="Дата создания категории",
        auto_now_add=True,
    )
    counter = models.IntegerField(
        verbose_name="Индекс для нового документа",
        default=1,
        help_text="Введите номер для нового элемента данной категории",
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["-date_created"]

    def __str__(self):
        return self.name


class Doc(models.Model):
    date_created = models.DateTimeField(
        verbose_name="Дата создания документа",
        auto_now_add=True,
    )
    data_doc = models.DateTimeField(
        verbose_name="Дата документа",
        help_text="Введите дату документа",
        null=True,
    )
    name = models.CharField(
        max_length=100,
        verbose_name="Наименование документа",
        help_text="Введите наименование документа",
    )
    number = models.CharField(
        max_length=10,
        verbose_name="Номер документа",
        help_text="Введите номер документа",
    )
    category = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        related_name="docs",
    )
    file_doc = models.FileField(
        upload_to="",
        verbose_name="Путь до файла документа",
        help_text="Укажите путь до файла документа",
    )

    class Meta:
        verbose_name = "Документ"
        verbose_name_plural = "Документы"
        ordering = ["-date_created"]

    def __str__(self):
        return self.name[:10]

arhidoc/docbase/forms.py
from django import forms
from .models import Doc


class DocForm(forms.ModelForm):
    class Meta:
        model = Doc
        fields = (
            "name",
            "number",
            "data_doc",
            "file_doc",
            "category",
        )


class SearcheForm(forms.Form):
    name = forms.CharField(label="Наименование документа", required=False)
    number = forms.CharField(label="Номер документа", required=False)
    data_doc = forms.CharField(label="Дата документа", required=False)

arhidoc/docbase/views.py
import os
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.conf import settings

from .models import Doc, Category
from .forms import DocForm, SearcheForm


def index(request):
    documents = Doc.objects.order_by("-date_created")
    count = documents.count()
    paginator = Paginator(documents, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "docbase/list.html", {"page_obj": page_obj, "count": count}
    )


def all_category(request):
    category = Category.objects.all()
    return render(request, "docbase/category.html", {"page_obj": category})


def docs_category(request, pk):
    documents = Doc.objects.filter(category=pk).order_by("-date_created")
    count = documents.count()
    paginator = Paginator(documents, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, "docbase/list.html", {"page_obj": page_obj, "count": count}
    )


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            response = HttpResponse(
                fh.read(),
                content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            )
            response[
                "Content-Disposition"
            ] = "inline; filename=" + os.path.basename(file_path)
            return response
    raise Http404


def searche(request):
    if request.method == "POST":
        form = DocForm(request.POST, request.FILES)
        validate_data = form.data
        name = validate_data["name"].strip()
        number = validate_data["number"].strip().upper()
        data_doc = validate_data["data_doc"].strip()
        page_obj = (
            Doc.objects.filter(data_doc__contains=data_doc)
            .filter(name__contains=name)
            .filter(number__contains=number)
        )
        count = page_obj.count
        return render(
            request,
            "docbase/list.html",
            {"page_obj": page_obj, "count": count},
        )
    else:
        form = SearcheForm()
    return render(request, "core/searche.html", {"form": form})


def create_docs(request, pk):
    error = False
    if request.method == "POST":
        form = DocForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            counter = Category.objects.filter(id=pk).first().counter + 1
            Category.objects.filter(id=pk).update(counter=counter)
            return redirect("docbase:main")
        else:
            error = True
    else:
        counter = Category.objects.filter(id=pk).first().counter
        name = Category.objects.filter(id=pk).first().name
        if counter < 10:
            counter = "0" + str(counter)
        number = "{}-{}".format(counter, name)
        form = DocForm()
        form.fields["number"].initial = number
        form.fields["category"].initial = Category.objects.filter(
            id=pk
        ).first()
    return render(
        request,
        "core/model_form_upload.html",
        {"form": form, "error": error},
    )


def model_form_upload(request):
    if request.method == "POST":
        form = DocForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("docbase:main")
    else:
        form = DocForm()
    return render(request, "core/model_form_upload.html", {"form": form})

arhidoc/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="msapplication-TileColor" content="#000" />
    <meta name="theme-color" content="#ffffff" />
  </head>
  <body class="container py-5">
    {% include 'includes/header.html' %}
    <main>{% block content %} Контент не подвезли :( {% endblock %}</main>
    <footer>{% include 'includes/footer.html' %}</footer>
  </body>
</html>

arhidoc/templates/core/model_form_upload.html
{% extends 'base.html' %} {% block content %}
<div class="container" style="padding-top: 26px">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% if error %}
    <p>Введите корректные данные</p>
    {% endif %}
    <table class="table table-sm table-striped table-hover table-bordered border-primary">
      <tbody>
        <tr>
          <td style="width: 20%"><b>{{ form.category.label_tag }}</b></td>
          <td style="width: 15%">
            <b><span style="color: red">{{ name }}{{ form.category }}</span></b>
          </td>
          <td style="width: 65%"><b>{{ form.category.help_text|safe }}</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.name.label_tag }}</b></td>
          <td style="width: 15%"><b>{{ form.name }}</b></td>
          <td style="width: 65%"><b>{{ form.name.help_text|safe }}</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.number.label_tag }}</b></td>
          <td style="width: 15%"><b>{{ form.number }}</b></td>
          <td style="width: 65%"><b>{{ form.number.help_text|safe }}</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.data_doc.label_tag }}</b></td>
          <td style="width: 15%"><b>{{ form.data_doc }}</b></td>
          <td style="width: 65%"><b>{{ form.data_doc.help_text|safe }} в формате YYYY-MM-DD</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.file_doc.label_tag }}</b></td>
          <td style="width: 15%"><b>{{ form.file_doc }}</b></td>
          <td style="width: 65%"><b>{{ form.file_doc.help_text|safe }}</b></td>
        </tr>
      </tbody>
    </table>
    <button type="submit" class="btn rounded-pill" style="background-color: #a370f7">Загрузить</button>
  </form>
</div>
{% endblock %}

arhidoc/templates/core/searche.html
{% extends 'base.html' %} {% block content %}
<div class="container" style="padding-top: 26px">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p><b>Введите поля для поиска документов</b></p>
    <table class="table table-sm table-striped table-hover table-bordered border-primary">
      <tbody>
        <tr>
          <td style="width: 20%"><b>{{ form.name.label_tag }}</b></td>
          <td style="width: 80%"><b>{{ form.name }}</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.number.label_tag }}</b></td>
          <td style="width: 80%"><b>{{ form.number }}</b></td>
        </tr>
        <tr>
          <td style="width: 20%"><b>{{ form.data_doc.label_tag }}</b></td>
          <td style="width: 80%"><b>{{ form.data_doc }}</b></td>
        </tr>
      </tbody>
    </table>
    <button type="submit" class="btn rounded-pill" style="background-color: #a370f7">Поиск</button>
  </form>
</div>
{% endblock %}

arhidoc/templates/docbase/category.html
{% extends 'base.html' %} {% block content %} {% for char in page_obj %} {% if forloop.first %}
<p style="padding-top: 10px; font-size: 35px">Категории</p>
<table class="table table-sm table-striped table-hover table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">№</th>
      <th scope="col">Наименование</th>
      <th scope="col">Счётчик</th>
      <th scope="col">Функции</th>
      <th scope="col">Функции</th>
    </tr>
  </thead>
  {% endif %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td><b>{{ char.name }}</b></td>
      <td>{{ char.counter }}</td>
      <td>
        <a class="btn btn-outline-dark" href="{% url 'docbase:docs_category' char.id %}">Все документы категории</a>
      </td>
      <td>
        <a class="btn btn-outline-dark" href="{% url 'docbase:create_docs' char.id %}">Создать документ</a>
      </td>
    </tr>
    {% if forloop.last %}
  </tbody>
</table>
{% endif %} {% empty %}
<p>Если цикл пуст</p>
{% endfor %} {% endblock %}

arhidoc/templates/docbase/list.html
{% extends 'base.html' %} {% block content %} {% for char in page_obj %} {% if forloop.first %}
<p style="padding-top: 10px; font-size: 35px">Документы. Всего {{ count }}</p>
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1" class="btn rounded-pill" style="background-color: #a370f7">&laquo;</a>
    <a href="?page={{ page_obj.previous_page_number }}" class="btn rounded-pill" style="background-color: #a370f7"
      >Назад</a
    >
    {% endif %}
    <span class="btn rounded-pill" style="background-color: #a370f7">
      Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn rounded-pill" style="background-color: #a370f7"
      >Вперед</a
    >
    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn rounded-pill" style="background-color: #a370f7"
      >&raquo;</a
    >
    {% endif %}
  </span>
</div>
<p></p>
<table class="table table-sm table-striped table-hover table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Наименование</th>
      <th scope="col">Дата</th>
      <th scope="col">Номер</th>
      <th scope="col">Категория</th>
      <th scope="col">Скачать</th>
    </tr>
  </thead>
  <tbody>
    {% endif %}
    <tr>
      <td style="width: 5%">{{ char.id }}</td>
      <td style="width: 75%"><b>{{ char.name }}</b></td>
      <td style="white-space: nowrap">{{ char.data_doc|date:'Y-m-d' }}</td>
      <td style="width: 5%">{{ char.number }}</td>
      <td style="width: 5%">{{ char.category }}</td>
      <td style="width: 5%">
        <a
          href="{% url 'docbase:load' char.file_doc %}"
          download
          class="btn rounded-pill"
          style="background-color: #a370f7"
          role="button"
          >LOAD</a
        >
      </td>
    </tr>
    {% if forloop.last %}
  </tbody>
</table>
{% endif %} {% empty %}
<p style="padding-top: 30px; font-size: 35px"><b>НЕТ ДАННЫХ</b></p>
{% endfor %} {% endblock %}

arhidoc/templates/includes/header.html
<header>
  <nav class="navbar navbar-light fixed-top" style="background-color: #a370f7">
    <div class="container-fluid">
      <ul class="nav">
        <li class="nav nav-item" style="padding-right: 6px">
          <a class="btn btn-dark" href="{% url 'docbase:main' %}" role="button">ARHIdoc v0.8</a>
        </li>
        <li class="nav nav-item" style="padding-right: 6px">
          <a class="btn btn-outline-dark" href="{% url 'docbase:main' %}" role="button">Документы</a>
        </li>
        <li class="nav nav-item" style="padding-right: 6px">
          <a class="btn btn-outline-dark" href="{% url 'docbase:all_category' %}" role="button">Категории</a>
        </li>
        <li class="nav nav-item" style="padding-right: 6px">
          <a class="btn btn-outline-dark" href="{% url 'docbase:searche' %}" role="button">Поиск</a>
        </li>
        <li class="nav nav-item" style="padding-right: 6px">
          <a class="btn btn-outline-dark" href="/admin/" role="button">Панель администратора</a>
        </li>
      </ul>
    </div>
  </nav>
</header>